[tool.black]
line-length = 125
skip-string-normalization = true

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
line_length = 125

[tool.pyright]
reportUnnecessaryTypeIgnoreComment = "warning"
pythonVersion = "3.10"
typeCheckingMode = "basic"
strictParameterNoneValue = false
include = ["cogs"]
exclude = ["**/__pycache__", "build", "dist"]

[tool.ruff]
line-length = 150
select = [
    'A',
    'ASYNC',
    'B',
    'C',
    'COM',
    'E',
    'EM',
    'F',
    'FA',
    'G',
    'PL',
    'Q',
    'T10',
    'UP',
    'W',
]
ignore = ['A003', 'D105', 'D107', 'D401', "F403", "F405", "E501", "PLR2004"]
target-version = "py310"
exclude = ["discord"]
format = "text"

[tool.ruff.mccabe]
max-complexity = 35

[tool.ruff.pylint]
max-args = 15
max-branches = 35
max-returns = 15
max-statements = 80
